2025-06-18 08:46:16,464 INFO: Auth header: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVlYTU5OWI0LTg4N2UtNDVjZS1hYWY0LTc0OTA0YzI1Yjk1MiIsImVtYWlsIjoiaHlhdHQuam9uYXRoYW45OUBnbWFpbC5jb20iLCJleHAiOjE3NTA4NTg3NDR9.AP5fKMuf2nMocgbTQ5RKuhf_ReFXD5YgAVcDtG8Ugeo [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:700]
2025-06-18 08:46:16,467 INFO: Verifying token: eyJhbGciOi... [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:711]
2025-06-18 08:46:16,467 INFO: Decoded token: {'id': 'eea599b4-887e-45ce-aaf4-74904c25b952', 'email': 'hyatt.jonathan99@gmail.com', 'exp': 1750858744} [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:716]
2025-06-18 08:46:16,467 INFO: Using admin client to fetch stored recommendations [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:1481]
2025-06-18 08:46:17,029 INFO: Stored recommendations found: 0 [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:1499]
2025-06-18 08:46:17,033 INFO: Auth header: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVlYTU5OWI0LTg4N2UtNDVjZS1hYWY0LTc0OTA0YzI1Yjk1MiIsImVtYWlsIjoiaHlhdHQuam9uYXRoYW45OUBnbWFpbC5jb20iLCJleHAiOjE3NTA4NTg3NDR9.AP5fKMuf2nMocgbTQ5RKuhf_ReFXD5YgAVcDtG8Ugeo [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:700]
2025-06-18 08:46:17,034 INFO: Verifying token: eyJhbGciOi... [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:711]
2025-06-18 08:46:17,034 INFO: Decoded token: {'id': 'eea599b4-887e-45ce-aaf4-74904c25b952', 'email': 'hyatt.jonathan99@gmail.com', 'exp': 1750858744} [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:716]
2025-06-18 08:46:17,034 INFO: Using admin client to fetch stored recommendations [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:1481]
2025-06-18 08:46:17,226 INFO: Stored recommendations found: 0 [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:1499]
2025-06-18 08:46:26,895 ERROR: Unhandled exception [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:1967]
Traceback (most recent call last):
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask/app.py", line 915, in full_dispatch_request
    rv = self.preprocess_request()
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask/app.py", line 1291, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask_limiter/extension.py", line 1180, in _check_request_limit
    raise e
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask_limiter/extension.py", line 1177, in _check_request_limit
    self.__evaluate_limits(endpoint, all_limits)
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask_limiter/extension.py", line 1161, in __evaluate_limits
    raise RateLimitExceeded(
flask_limiter.errors.RateLimitExceeded: 429 Too Many Requests: 50 per 1 hour
2025-06-18 08:46:26,897 ERROR: Unhandled exception [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:1967]
Traceback (most recent call last):
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask/app.py", line 915, in full_dispatch_request
    rv = self.preprocess_request()
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask/app.py", line 1291, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask_limiter/extension.py", line 1180, in _check_request_limit
    raise e
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask_limiter/extension.py", line 1177, in _check_request_limit
    self.__evaluate_limits(endpoint, all_limits)
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask_limiter/extension.py", line 1161, in __evaluate_limits
    raise RateLimitExceeded(
flask_limiter.errors.RateLimitExceeded: 429 Too Many Requests: 50 per 1 hour
2025-06-18 08:46:26,899 ERROR: Unhandled exception [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:1967]
Traceback (most recent call last):
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask/app.py", line 915, in full_dispatch_request
    rv = self.preprocess_request()
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask/app.py", line 1291, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask_limiter/extension.py", line 1180, in _check_request_limit
    raise e
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask_limiter/extension.py", line 1177, in _check_request_limit
    self.__evaluate_limits(endpoint, all_limits)
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask_limiter/extension.py", line 1161, in __evaluate_limits
    raise RateLimitExceeded(
flask_limiter.errors.RateLimitExceeded: 429 Too Many Requests: 50 per 1 hour
2025-06-18 08:46:26,903 ERROR: Unhandled exception [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:1967]
Traceback (most recent call last):
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask/app.py", line 915, in full_dispatch_request
    rv = self.preprocess_request()
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask/app.py", line 1291, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask_limiter/extension.py", line 1180, in _check_request_limit
    raise e
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask_limiter/extension.py", line 1177, in _check_request_limit
    self.__evaluate_limits(endpoint, all_limits)
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask_limiter/extension.py", line 1161, in __evaluate_limits
    raise RateLimitExceeded(
flask_limiter.errors.RateLimitExceeded: 429 Too Many Requests: 50 per 1 hour
2025-06-18 08:47:28,656 INFO: Auth header: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVlYTU5OWI0LTg4N2UtNDVjZS1hYWY0LTc0OTA0YzI1Yjk1MiIsImVtYWlsIjoiaHlhdHQuam9uYXRoYW45OUBnbWFpbC5jb20iLCJleHAiOjE3NTA4NTg3NDR9.AP5fKMuf2nMocgbTQ5RKuhf_ReFXD5YgAVcDtG8Ugeo [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:700]
2025-06-18 08:47:28,656 INFO: Verifying token: eyJhbGciOi... [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:711]
2025-06-18 08:47:28,656 INFO: Decoded token: {'id': 'eea599b4-887e-45ce-aaf4-74904c25b952', 'email': 'hyatt.jonathan99@gmail.com', 'exp': 1750858744} [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:716]
2025-06-18 08:47:28,657 INFO: Using admin client to fetch recommendation history [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:1531]
2025-06-18 08:47:29,167 INFO: History data count: 0 [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:1546]
2025-06-18 08:47:29,171 INFO: Auth header: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVlYTU5OWI0LTg4N2UtNDVjZS1hYWY0LTc0OTA0YzI1Yjk1MiIsImVtYWlsIjoiaHlhdHQuam9uYXRoYW45OUBnbWFpbC5jb20iLCJleHAiOjE3NTA4NTg3NDR9.AP5fKMuf2nMocgbTQ5RKuhf_ReFXD5YgAVcDtG8Ugeo [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:700]
2025-06-18 08:47:29,171 INFO: Verifying token: eyJhbGciOi... [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:711]
2025-06-18 08:47:29,172 INFO: Decoded token: {'id': 'eea599b4-887e-45ce-aaf4-74904c25b952', 'email': 'hyatt.jonathan99@gmail.com', 'exp': 1750858744} [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:716]
2025-06-18 08:47:29,172 INFO: Using admin client to fetch recommendation history [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:1531]
2025-06-18 08:47:29,383 INFO: History data count: 0 [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:1546]
2025-06-18 08:48:21,087 ERROR: Unhandled exception [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:1967]
Traceback (most recent call last):
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask/app.py", line 915, in full_dispatch_request
    rv = self.preprocess_request()
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask/app.py", line 1291, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask_limiter/extension.py", line 1180, in _check_request_limit
    raise e
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask_limiter/extension.py", line 1177, in _check_request_limit
    self.__evaluate_limits(endpoint, all_limits)
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask_limiter/extension.py", line 1161, in __evaluate_limits
    raise RateLimitExceeded(
flask_limiter.errors.RateLimitExceeded: 429 Too Many Requests: 50 per 1 hour
2025-06-18 08:48:21,088 ERROR: Unhandled exception [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:1967]
Traceback (most recent call last):
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask/app.py", line 915, in full_dispatch_request
    rv = self.preprocess_request()
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask/app.py", line 1291, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask_limiter/extension.py", line 1180, in _check_request_limit
    raise e
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask_limiter/extension.py", line 1177, in _check_request_limit
    self.__evaluate_limits(endpoint, all_limits)
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask_limiter/extension.py", line 1161, in __evaluate_limits
    raise RateLimitExceeded(
flask_limiter.errors.RateLimitExceeded: 429 Too Many Requests: 50 per 1 hour
